export const UTILS_CONSTANTS = {
    NODE_ENV: 'NODE_ENV',
    HOST: 'HOST',
    PORT: 'PORT',
    USERNAME: 'USERNAME',
    PASSWORD: 'PASSWORD',
    DATABASE: 'DATABASE',
    HOST_BD: 'HOST_BD',
    PORT_BD: 'PORT_BD',

    JWT_SECRET: 'JWT_SECRET',
    JWT_TIME_LOGIN: 'JWT_TIME_LOGIN'

}